### ISSUE TITLE
Couldn't switch context on official L

### ISSUE THREAD

**Issue by thuantran** [Stericson/RootTools#25]
Hi there,

I'm using the current latest stable version of roottools and I can't switch context using this code:

RootTools.getShell(true, ShellContext.UNTRUSTED_APP).add(cc);

Regardless what ShellContext constant I use, I still only get the normal init context as the output of id is like this: uid=0(root) gid=0(root) context=u:r:init:s0

I tested this on Nexus 5 with CFAR and latest SuperSU with LPX21O.

**Comment by thuantran** [comment]
Still the same problem even in Android Studio as I moved my projects over. I also tried your new RootShell same issue with the jar. I will report this issue there and will double check this SELinux with plain library source until you have this fixed.

**Comment by thuantran** [comment]
The context switching issue seems to be fixed in RootShell for me, thanks.

I don't know why but you've "blow out" your code in RootShell project so in the mean time I will report stuffs regarding the jar issue here until further notice.

**Comment by Stericson** [comment]
Thanks!

yea, sorry about that. I was working on it...I'm horrible at commit messages.

I've pushed everything back in. So you should see all of the code.
