### ISSUE TITLE
How to finish a command

### ISSUE THREAD

**Issue by MFlisar** [Stericson/RootTools#41]
If I execute a set of commands, `commandCompleted` is never called. Do I have to call it manually? I tried adding a `exit\n` command, but that does not solve the problem either. Following works, but it's just a workaround. How is meant to be used correctly?

```
Command command = new Command(0, true, getCommandSu(), "ps\n", "echo EXIT") {
        @Override
        public void commandOutput(int id, String line) {
            // use cmd output...

            // finish command
            if (line.equals("EXIT"))
                commandFinished();
        }

        @Override
        public void commandCompleted(int id, int exitCode) {
            L.d("COMPLETED (" + exitCode + ")");
        }
    };
    shell.runCommand(command);
    while (!command.isFinished()) {
        Thread.sleep(50);
    }
```

**Comment by Stericson** [comment]
Normally you wouldn't call this method directly. However, the logic you have implemented should work.

2 things here:

1. You should be calling the super method for commandOuput

2. Can you debug your if condition and ensure commandFinished is being called?

**Comment by MFlisar** [comment]
I will try 1 - makes sense anywayd... And to 2, yes, this works perfectly fine, my commandFinished is called if I do it this way...

**Comment by zhuoensea** [comment]
Hi, I'd like to know that if there is a way to send "ctrl + c" with RootTools? @Stericson 
For example, in the shell:
`logcat > /sdcard/mylogcat.txt`
to output logcat, and:
`^C`
Control-C for finishing outputting.
I have tried `finish();` with RootTools 4.2, it seems finishing all the command but nothing output in mylogcat.txt.
