### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by axierjhtjz** [Stericson/RootTools#42]
Hi! I´ve updated this part of the [Usage page on the wiki](https://github.com/Stericson/RootTools/wiki/Usage/_compare/1080f13ba133e79ea0b6bb05d4465e17fb276913%5E...1080f13ba133e79ea0b6bb05d4465e17fb276913) and I think that the first part o [Running root commands](https://github.com/Stericson/RootTools/wiki/Usage#running-root-commands)  should be updated too since there is no `CommandCapture` option.

Should it be updated from
````
CommandCapture command = new CommandCapture(0, "echo this is a command", "echo this is another command");
RootTools.getShell(true).add(command).waitForFinish();
````

to

```
Command command = new Command(0, "settings put secure user_setup_complete 0", "settings put global device_provisioned 0");
RootTools.getShell(true).add(command);
```

I don't mind updating this part but I want to know first if I´m doing something wrong or CommanCapture belogs to a legacy version of the library :smile:

**Comment by Stericson** [comment]
You are correct. I've updated the usage wiki, thanks :)

**Comment by axierjhtjz** [comment]
You're welcome ;)
