### ISSUE TITLE
Cannot resolve symbol 'CommandCapture'

### ISSUE THREAD

**Issue by DanMossa** [Stericson/RootTools#48]
I'm trying to create a root app and I found out about `RootTools`.

https://github.com/Stericson/RootTools/releases

I went ahead and downloaded the `RootTools.jar`

I followed this guide to import `RootTools.jar`

> In your project, choose File menu > Project Structure (there's a bug
> in 0.4.4 and this menu item won't have a title at all; it still works)
> 
> > Modules > choose your module > Dependencies > + button > File dependency > choose your library from the file picker. That file needs
> > to be somewhere beneath the root directory of your projet; the libs
> > directory is fine.

I now put 

```
CommandCapture command = new CommandCapture(0, "cp -f " + sourceLocation + " " + targetLocation);
RootTools.getShell(true).add(command);
```

Inside my code, the issue with this is that CommandCapture is highlighted in red and I get an issue saying that this symbol is not resolved

[![http://i.imgur.com/x2wlu46.png](http://i.stack.imgur.com/ZrLt8.png)](http://i.stack.imgur.com/ZrLt8.png)

This is my whole code so far.

```
package dgameman1.com.emojiupdaterroot;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.Spinner;

import com.stericson.RootTools.RootTools;

import java.io.IOException;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

       // final Spinner emojiSpinner = (Spinner) findViewById(R.id.emojiSpinner);
        final Button updateEmojiButton = (Button) findViewById(R.id.updateEmojiButton);

        updateEmojiButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                try {
                    CommandCapture command = new CommandCapture(0, "cp -f " + sourceLocation + " " + targetLocation);
                    RootTools.getShell(true).add(command);
                } catch (IOException e) {
                }
            }
        });
    }
}
```

**Comment by Fusion** [comment]
Hi.

Try `Command` instead of `CommandCapture`

The library went through a massive code re organization and while it is now cleaner this means a few things have changed. For instance, the tools' kernel is found under RootShell, meaning that the newly renamed `Command` class belongs to `com.stericson.rootshell.execution`

**Comment by Dgameman1** [comment]
Oh! Thanks :+1:
