### ISSUE TITLE
Gradle repo

### ISSUE THREAD

**Issue by dron247** [Stericson/RootTools#65]
Hi, could you maintain a repo for your releases?
It's very handy to add it into project by single line of code
`compile 'org.stericson:roottools:4.2.0'`

**Comment by rahulkumar66** [comment]
@Stericson is there a repo for roottools for gradle yet?

**Comment by BRoy98** [comment]
You can use jitpack.io package repository which can hosts any public git repo.

Add it to your root build.gradle at the end of repositories:
```
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}
```

Then, for latest updates add this dependency 

`implementation 'com.github.Stericson:RootTools:-SNAPSHOT'`

or mention any release

`implementation 'com.github.Stericson:RootTools:5.0'`

**Comment by tibbi** [comment]
This should definitely be sorted out if you want people to use the library. Together with adding a README with setup instructions.

**Comment by MFlisar** [comment]
For me only this works: 

    implementation 'com.github.Stericson:RootShell:1.6'
    implementation ('com.github.Stericson:RootTools:5.0') {
        exclude group: 'com.github.Stericson'
    }

RootTools 5.0 depends on RootShell 5.0 (like this pom file says: https://jitpack.io/com/github/Stericson/RootTools/5.0/RootTools-5.0.pom), so this dependency must be corrected manually  as this repo is using the aar file directly and is not set up correctly for jitpack...

**Comment by Stericson** [comment]
Jitpack support added in latest commits
