### ISSUE TITLE
execute code ( not command ) as root

### ISSUE THREAD

**Issue by oabukmail** [Stericson/RootTools#69]
Hello All

is it possible to execute part of code ( not commands ) as root 

i have a code to open socket in deep of the system , and it gives permission denied 

is it possible to run it as root ?

**Comment by Fusion** [comment]
If you mean Java code, then the process is a tad involved but you can find how to do this here: https://github.com/Stericson/RootTools/wiki/Java-as-root

**Comment by bigthugs0** [comment]
ya , i saw this after posting the issue

but im still trying to make it work with android studio project structure 
since the RootClass still work with android studio structure
