### ISSUE TITLE
remount command not working

### ISSUE THREAD

**Issue by AnuthaDev** [Stericson/RootTools#80]
I am trying to remount the /system, but it is not working:
public void remount(View v){
Log.d(TAG, "Starting remount...");
Root tools.remount("/system/", "rw");
Log.d(TAG, "Remount Complete");
}
But the last line of code is never executed and my app gets an ant error. Please help

**Comment by Anutha02** [comment]
*app not responding error....

**Comment by Nike1016** [comment]
1
