### ISSUE TITLE
Failed to resolve: com.github.stericson:RootShell:5.0

### ISSUE THREAD

**Issue by robross0606** [Stericson/RootTools#84]
Attempting to pull RootTools in via JitPack results in the following Gradle error:
```
Failed to resolve: com.github.stericson:RootShell:5.0
```
I know RootShell is only at version 1.6 so I'm assuming there is some sort of dependency issue in the Jitpack package.

**Comment by JcChimjj** [comment]
RootShell：5.0 ＃84
