### ISSUE TITLE
how correctly add RootTools library to Android Studio

### ISSUE THREAD

**Issue by lynda18** [Stericson/RootTools#88]
Hi all, 
I've tried to add RootTools lib to my project in either of the following ways:

1. as a **jitpack** dependency ([according to](https://jitpack.io/#stericson/roottools))

2. Download the latest RootTools library ([from here](https://github.com/Stericson/RootTools/releases)) and import the library **module** to my project

3. Add the compiled **AAR** file of **RootShell** side of imported library module of RootTools

but I did not succeed.

I used #87 solution , but can not I use the main branch?

Thanks in advance for your help and guidance.

**Comment by RomanTsarou** [comment]
Try add it to your dependencies:
```groovy
    implementation('com.github.Stericson:RootTools:5.0') { transitive = false }
    implementation 'com.github.Stericson:RootShell:1.6'
```

**Comment by lynda18** [comment]
> 
> 
> Try add it to your dependencies:
> 
> ```groovy
>     implementation('com.github.Stericson:RootTools:5.0') { transitive = false }
>     implementation 'com.github.Stericson:RootShell:1.6'
> ```

It Worked For Me like a charm. Thank you for your consideration and guidance 👍.
